params:
  event_types:
    - CommitCommentEvent
    - CreateEvent
    - DeleteEvent
    - ForkEvent
    - GollumEvent
    - IssueCommentEvent
    - IssuesEvent
    - MemberEvent
    - PublicEvent
    - PushEvent
    - PullRequestEvent
    - PullRequestReviewEvent
    - PullRequestReviewCommentEvent
    - PullRequestReviewThreadEvent
    - ReleaseEvent
    - SponsorshipEvent
    - WatchEvent
  active_event_type: WatchEvent
  
gcs_bucket_config:
  storage_class: NEARLINE
  lifecycle_delete_rule_age: 7 # Number of Days


